# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/bannisjack/ALU/ALU.cache/wt [current_project]
set_property parent.project_path C:/Users/bannisjack/ALU/ALU.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part digilentinc.com:nexys4_ddr:part0:1.1 [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
read_vhdl -library xil_defaultlib {
  C:/Users/bannisjack/ALU/ALU.srcs/sources_1/new/FullAdder.vhd
  C:/Users/bannisjack/ALU/ALU.srcs/sources_1/imports/new/ssd_decoder.vhd
  C:/Users/bannisjack/ALU/ALU.srcs/sources_1/new/Adder4Bit.vhd
  C:/Users/bannisjack/ALU/ALU.srcs/sources_1/new/ALU_TOP.vhd
}
read_xdc C:/Users/bannisjack/ALU/ALU.srcs/constrs_1/new/Constraints.xdc
set_property used_in_implementation false [get_files C:/Users/bannisjack/ALU/ALU.srcs/constrs_1/new/Constraints.xdc]

synth_design -top ALU_TOP -part xc7a100tcsg324-1
write_checkpoint -noxdef ALU_TOP.dcp
catch { report_utilization -file ALU_TOP_utilization_synth.rpt -pb ALU_TOP_utilization_synth.pb }
